version: '3'
services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.10-bookworm
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    build:
      context: .
      dockerfile: Dockerfile
    links:
    - test

  test:
    image: mcr.microsoft.com/devcontainers/python:1-3.10-bookworm
    volumes:
      - .:/workspace:cached
    build:
      context: .
      dockerfile: Dockerfile_test

